name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cdk-build:
    name: CDK Build and Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: paroduction/node_modules
          key: ${{ runner.os }}-production-${{ hashFiles('production/package-lock.json') }}
          restore-keys: ${{ runner.os }}-production-
      - name: npm install
        run: npm install
      - name: compile typescript
        run: npm run build
      - name: synth cloudformation template
        run: npm run cdk synth -- -c version=${{ github.sha }} -c stackname=test
      - name: run cdk tests
        run: npm run test 
